FROM node:20.9.0-alpine

#RUN echo "20.201.28.151 github.com" >> /etc/hosts
#RUN echo "20.201.28.151 www.github.com" >> /etc/hosts
#RUN echo "121.37.144.64  registry.npmjs.org" >> /etc/hosts

COPY ht-flow-server /

RUN cp env-pre  .env

RUN npm install
RUN npm i -g @nestjs/cli
RUN npm run build

CMD [ "npm", "run", "start:prod" ]
